---
title: "linear models"
author: "Duzhi Zhao"
date: "11/7/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

# NYC airbnb dataset
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

## Fit a first linear model
```{r}
# Keeping boro fixed, how much price increases as one unit of stars increases
fit = lm(price ~ stars + boro, data = nyc_airbnb)
# if star goes up by one unit, price goes up by 31.99 dollars 

summary(fit)
coef(fit)
summary(fit)$coef
```

## tidy the results instead!
```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

## Take a look at factors
```{r}
# Factor ordered based on frequency. 1: most frequent
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type)
  )

# factor 1: most common ---- Manhattan
```

## Refit the last model
```{r}
fit = lm(price~ stars + boro, data = nyc_airbnb)

# Now the reference category is the most frequent factor: Manhattan instead of Bronx
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: "))

# p-value: is this regression coefficient significant?
```

## broom::glance()
```{r}
# p-value here: F stats to the whole model
fit %>% 
  broom::glance()
```

## Diagnostics
```{r}
# The modelr package can be used to add residuals and fitted values to a dataframe.

# add the model info to the originial dataset
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) +
  geom_violin() + 
  ylim(-500, 500)

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point() + 
  ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = pred)) +
  geom_point()
```

## Nesting data
```{r}
fit_interaction = lm(price ~ stars * boro, data = nyc_airbnb)
fit_interaction %>% 
  broom::tidy()
# price depends more stars; in bronx, brooklyn queens, star does not influence price much

# star ratings and room type affects price differently in each borough
fit_interaction = lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb)
fit_interaction %>% 
  broom::tidy()
# Output: the expected change in price comparing an entire apartment to a private room in Queens, for example, involves the main effect of room type and the Queens / private room interaction
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = .) %>% 
  broom::tidy()
```

## Map this instead
```{r}
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(boro, results) %>% 
  unnest(results)
```

## Nest neighborhoods
```{r}
manhattan_nest_lm_res =
  nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(results)

# plot
manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```


